services:
  wyl:
    image: aceberg/watchyourlan
    network_mode: "host"        
    restart: unless-stopped
    volumes:
    - ./watchyourlan/data:/data
    environment:
      TZ: America/Denver         # required: needs your TZ for correct time
      IFACE: "ens18" # required: 1 or more interface
      DBPATH: "/data/db.sqlite"         # optional, default: /data/db.sqlite
      GUIIP: "0.0.0.0"                  # optional, default: localhost
      GUIPORT: "8840"                   # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 60
      SHOUTRRR_URL: ""                  # optional, set url to notify
      THEME: "darkly"                   # optional
      IGNOREIP: "no"                    # optional
