---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      # - LOG_LEVEL=DEBUG
      - HOMEPAGE_VAR_PROXMOX_USERNAME=$HOMEPAGE_VAR_PROXMOX_USERNAME
      - HOMEPAGE_VAR_PROXMOX_PASSWORD=$HOMEPAGE_VAR_PROXMOX_PASSWORD
      - HOMEPAGE_VAR_TRUENAS_KEY=$HOMEPAGE_VAR_TRUENAS_KEY
      - HOMEPAGE_VAR_OPNSENSE_USERNAME=$HOMEPAGE_VAR_OPNSENSE_USERNAME
      - HOMEPAGE_VAR_OPNSENSE_PASSWORD=$HOMEPAGE_VAR_OPNSENSE_PASSWORD
      - HOMEPAGE_VAR_ADGUARD_USERNAME=$HOMEPAGE_VAR_ADGUARD_USERNAME
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=$HOMEPAGE_VAR_ADGUARD_PASSWORD
      - HOMEPAGE_VAR_UNIFI_USERNAME=$HOMEPAGE_VAR_UNIFI_USERNAME
      - HOMEPAGE_VAR_UNIFI_PASSWORD=$HOMEPAGE_VAR_UNIFI_PASSWORD
      - HOMEPAGE_VAR_IMMICH_KEY=$HOMEPAGE_VAR_IMMICH_KEY
      - HOMEPAGE_VAR_PBS_USERNAME=$HOMEPAGE_VAR_PBS_USERNAME
      - HOMEPAGE_VAR_PBS_PASSWORD=$HOMEPAGE_VAR_PBS_PASSWORD
      - HOMEPAGE_VAR_GRAFANA_USERNAME=$HOMEPAGE_VAR_GRAFANA_USERNAME
      - HOMEPAGE_VAR_GRAFANA_PASSWPRD=$HOMEPAGE_VAR_GRAFANA_PASSWORD
      - HOMEPAGE_VAR_PORTAINER_KEY=$HOMEPAGE_VAR_PORTAINER_KEY
      - HOMEPAGE_VAR_TAILSCALE_KEY=$HOMEPAGE_VAR_TAILSCALE_KEY
      - HOMEPAGE_VAR_AUTHENTIK_KEY=$HOMEPAGE_VAR_AUTHENTIK_KEY
      - HOMEPAGE_VAR_NEXTCLOUD_USERNAME=$HOMEPAGE_VAR_NEXTCLOUD_USERNAME
      - HOMEPAGE_VAR_NEXTCLOUD_PASSWORD=$HOMEPAGE_VAR_NEXTCLOUD_PASSWORD

    ports:
      - 3333:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      # - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    restart: unless-stopped
