services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8094:8080
    #command: --interval 86400 --debug list of containers to monitor
    environment:
      WATCHTOWER_DISABLE_CONTAINERS: "unifi nextcloud"
      WATCHTOWER_SCHEDULE: "0 0 1 * * *" #1 am everyday
      WATCHTOWER_CLEANUP: true
      # I probably will set this up with ntfy instead of using email
      # WATCHTOWER_NOTIFICATIONS: email
      # WATCHTOWER_NOTIFICATION_EMAIL_FROM: "email@yourdomain.com"
      # WATCHTOWER_NOTIFICATION_EMAIL_TO: "emailto@yourdomain.com"
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "smtppro.zoho.com"
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "email@yourdomain.com"
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "loginpass"
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "465"
      # WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      # WATCHTOWER_NOTIFICATIONS_HOSTNAME: "DockerHA"
      TZ: "America/Denver" 
      WATCHTOWER_NO_STARTUP_MESSAGE: true
      WATCHTOWER_HTTP_API_TOKEN: "CKbXEXJpWEa1CM6cbQ0y7VU6eav6edzAuZVX2EQ3OKXiEAJAtJzeAIyBhT8Z4SA5" #random generated token
      WATCHTOWER_HTTP_API_UPDATE: true
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: true
      WATCHTOWER_TIMEOUT: 30s
      
