---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank
  
- datetime:
    text_size: x1
    format:
        timeStyle: short
        hourCycle: h12
