services:
  teleport:
      image: public.ecr.aws/gravitational/teleport-distroless:16.1.0
      container_name: teleport
      ports:
        - "3080:3080"
        - "3023:3023"
        - "3024:3024"
        - "3025:3025"
      volumes:
        - ./config:/etc/teleport
        - ./data:/var/lib/teleport
      restart: unless-stopped
